### ISSUE TITLE
Would it be possible to explain the Methods a little bit?

### ISSUE THREAD

**Issue by escamoteur** [thihasoehtet/Jittuu.Rx.AddOn#1]
Hi,

Awesome functions, but it would be great if their purpose would be explained either in the readme or in the source. Some are quite obvious, but why an SubscribeAsync where Rx itself offers Async execution?

I think a lot of people will love this Addons!

What would be great if you could add a method RetryAfter<Exception>(Action)

Which can be achieved by RetryIf but with a slightly different semantic

All the best

Thomas

**Comment by thihasoehtet** [comment]
Hi Thomas,

Yes, I agree with you to have method explanations with some usage examples will be great and I'm going to work on that. Currently I'm maintaining this library alone but I'm welcome other contributors also.

For **RetryAfter**, I will take a look and I think the signature will be like

``` C#
IObservable<T> RetryAfter<T>(this IObservable<T> source, TimeSpan delayTime)
IObservable<T> RetryAfter<T>(this IObservable<T> source, TimeSpan delayTime, IScheduler scheduler)
```

Currently we can achieve this by using combo of **DelayError** and **Retry/RetryIf**.

If you have a pull request with unit test, just push it to me.

For **SubscribeAsync**, when we started this library, Rx haven't supported the Async yet. That's why we had this but it was named as **Subscribe** but after Rx supported Async it becomes conflict so I renamed it to **SubscribeAsync** and I feel that name is more explicit. And I'm planning to improve **SubscribeAsync** signature with **IAsyncObserver** like this

``` C#
IObservable<T> SubscribeAsync<T>(this IObservable<T> source, IAsyncObserver<T> observer)
```

Any suggestion and comment are welcome.

Warmest regards,
Thiha
